### ISSUE TITLE
Move static assets to alternative solution

### ISSUE THREAD

**Issue by Kentoseth** [OriginProtocol/origin-website#115]
As discussed in our chat today, we need to move all our static assets to a CDN.

**Comment by DanielVF** [comment]
This PR gives us the ability to move our PDF's files back to the site itself.

https://github.com/OriginProtocol/company-website/pull/126

**Comment by acal** [comment]
These seems like nice CDN options for a Flask site. The first link has Flask CNS code that can be used on a variety of servers including Amazon Cloudfront CDN.
https://github.com/libwilliam/flask-cdn
The second link is specific to implementing on Key CDN but uses the same git repo:
https://www.keycdn.com/support/flask-cdn-integration-guide/

**Comment by wanderingstan** [comment]
@DanielVF - given that #126 was merged, do we now need to do some work to move our assets back onto the site and off of amazon?

**Comment by DanielVF** [comment]
I would move where we send the visitors back.

**Comment by micahalcorn** [comment]
Resolved per @DanielVF 🐇
