### ISSUE TITLE
Feature all contributors on our team page

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/origin-website#154]
We should pull the combined list of our contributors from each of our Github repos and put your beautiful faces on our team page. Ideally it would be cached but self-updating as we get new contributors. We'll want to link back to each person's individual contributions to Origin on Github if possible.

@micahalcorn and Aure can figure out the design. :)

**Comment by coleman415** [comment]
![tyler](https://user-images.githubusercontent.com/25097802/38694457-8d841978-3e3e-11e8-8936-6f5430189f20.jpg)
<img width="200" alt="nick" src="https://user-images.githubusercontent.com/25097802/38694461-8ff8ded2-3e3e-11e8-8ee9-82d605335024.png">
![gagan](https://user-images.githubusercontent.com/25097802/38694462-9015ff58-3e3e-11e8-88b0-f218d0f2587e.png)
![brad](https://user-images.githubusercontent.com/25097802/38694463-9037ed20-3e3e-11e8-9afe-262cdcdda578.jpg)

Tyler is a full stack developer and blockchain enthusiast. He is a recent college graduate who has helped build an ecommerce platform in the auto recycling industry.

Nick is a XXXX

Gagan is a full Stack Developer with over 4 years of experience working with several early stage startups. Expertise in building scalable enterprise grade applications.

Brad is a full stack developer, product manager and entrepreneur. He is founder of real estate collaboration platform, BoxMLS  and a P2P used-goods marketplace, HashtagSell.

**Comment by joshfraser** [comment]
See the [Protocol Labs team section](https://protocol.ai/team/) for an example of what this could look like. Their code for is [open-source](https://github.com/ipfs/contributors) and looks pretty easy for us to integrate.

**Comment by micahalcorn** [comment]
Done long ago 💪
