### ISSUE TITLE
Developer landing page

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin-website#157]
As discussed, we should have a page for developers that gives more guidance than [Github's default page](https://github.com/originprotocol). 

## Basics to include:

- [x] Link to platform repo and explanation of origin.js
- [x] Link to demo-dapp repo and explanation
- [x] Link to bridge-server repo and explanation
- [x] Link to [docs](http://docs.originprotocol.com/)
- [x] Info on weekly engineering calls
- [x] CTA on joining #engineering on discord
- [x] Emphasize everything is MIT open-source

## Bonus
- [ ] Digram showing relation of repos/components (updated, simplified, and cleaned up version of [this one](https://drive.google.com/open?id=1tAtZX_uyAA7we6P1k7QoixM52V1xbeRr))
![image](https://user-images.githubusercontent.com/673455/38694733-3d6c1f34-3e3f-11e8-89c6-b8bd04c043fa.png)
- [x] Show time of engineering call in user's local timezone.
- [x] Link to iCal event for engineering call 

---

This graphic from slide deck may be good starting point for how we show the repos:
![image](https://user-images.githubusercontent.com/673455/38694699-28e1c9ec-3e3f-11e8-8dff-67e730f9144a.png)

---

@matthewliu - You said you could take a first stab at copy/content?

**Comment by davecraige** [comment]
As per Aure's request on 5/14, I took a copywriting pass on both V1 and V2 of these developer landing page mocks in Zeplin.  Please let me know if there is anything else you need.

**Comment by micahalcorn** [comment]
Thanks, @davecraige 😅 We are going to try to get to this tomorrow.

**Comment by micahalcorn** [comment]
A first pass at this has been deployed to https://originprotocol-com-micah.herokuapp.com/en/developers. @davecraige, feel free to offer critiques. 🙏

**Comment by micahalcorn** [comment]
Updated version: https://originprotocol-com-micah.herokuapp.com/en/developers

**Comment by davecraige** [comment]
Great.  Nice work Micah 🙌

**Comment by wanderingstan** [comment]
Great colors on the tags. :)

**Comment by davecraige** [comment]
![screen shot 2018-06-22 at 1 54 33 pm](https://user-images.githubusercontent.com/2782676/41796624-8577c338-7624-11e8-9c01-3cfee9457385.png)

Did you mean to say "#engineering channel"

![screen shot 2018-06-22 at 1 59 08 pm](https://user-images.githubusercontent.com/2782676/41796666-ac576454-7624-11e8-91e8-41a1e7d9b5fa.png)

I believe you said "create create" here.

![screen shot 2018-06-22 at 1 54 52 pm](https://user-images.githubusercontent.com/2782676/41796651-9efcabf2-7624-11e8-8ce7-d4286e79ca1d.png)

You may want to capitalize "Discord" here.

**Comment by micahalcorn** [comment]
Good eye, @davecraige. I'm doing too many things at once.

**Comment by davecraige** [comment]
:)

**Comment by davecraige** [comment]
(I can do a pull request as well when the code is up if there are any other small issues)

**Comment by micahalcorn** [comment]
@davecraige it actually looks like some of that stuff broke in a recent commit. Let me take a look.

**Comment by davecraige** [comment]
Ok, made those changes.  You should be able to find them here: 
https://github.com/OriginProtocol/origin-website/pull/220

**Comment by micahalcorn** [comment]
Thanks, @davecraige. I've linkify'd the repo names also: https://originprotocol-com-micah.herokuapp.com/en/developers Anything else you recommend?

**Comment by davecraige** [comment]
![screen shot 2018-06-22 at 2 44 02 pm](https://user-images.githubusercontent.com/2782676/41799244-f82950d2-762d-11e8-9a5a-39b52768b67f.png)

Small nitpick.  The buttons get a bit borked on mobile tablets set at 960 x 600.  (Might be super low priority as I see you are busy today)

**Comment by davecraige** [comment]
![screen shot 2018-06-22 at 3 11 43 pm](https://user-images.githubusercontent.com/2782676/41799407-a9312792-762e-11e8-90a9-fede622fb979.png)

Also from a copywriting perspective, there is a bit of lack of unity between these two sections of copy.  At the bottom in our footer we speak of "rent seeking middlemen" but the copy at the top says "trusted intermediaries". Seems as though the tone is lacking unity and it might be better to update the copy at the top to a similar tone.  

Here is another pass at that top paragraph copy:

"Origin is empowering developers to build decentralized marketplaces on the blockchain, which will allow buyers and sellers to meet and transact without requiring any intermediaries. Achieving this visionary goal requires contributions from a growing community of developers.  We would love for you to join us in this mission and help us."


(Also something we can also keep an eye on in the future is maybe linking the developers to our mission statement page.  The terms "radical inclusion and transparency" could be linked to this page in the future.)

**Comment by davecraige** [comment]
![screen shot 2018-06-22 at 3 34 23 pm](https://user-images.githubusercontent.com/2782676/41800197-c9ba9c66-7631-11e8-91e8-6e995d482dea.png)

Also any thoughts on having this say "Add to Google Calendar" for more granular clarity?  (Many people I know use Apple calendar.)

**Comment by micahalcorn** [comment]
I've updated the calendar link to use a Google icon for context.

**Comment by micahalcorn** [comment]
Ideas for future versions:

- shift to target DApp developers
- a short video tutorial
- [a code playground](https://github.com/OriginProtocol/origin-docs/issues/11)
- [the time zone map](http://docs.originprotocol.com/images/origin_engineering_call.png) for the engineering call (at the risk of it being incorrect as time brings change)
- a more [elaborate design](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5afa31e307e7b28148898232)
- a diagram of how our codebases interact

**Comment by micahalcorn** [comment]
First version done via https://github.com/OriginProtocol/origin-website/pull/222 ✅
