### ISSUE TITLE
Upgrade website to python 2.7.16

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin-website#188]
Deploying on heroku currently gives warning:
```
remote: -----> Python app detected
remote:  !     The latest version of Python 2 is python-2.7.15 (you are using python-2.7.14, which is unsupported).
remote:  !     We recommend upgrading by specifying the latest version (python-2.7.15).
remote:        Learn More: https://devcenter.heroku.com/articles/python-runtimes
```

**Comment by azban** [comment]
@wanderingstan i can take this.. seems like mostly a trivial change and then would involve just scoping out the heroku dev deploy before going to prod. is EnvKey setup to get the heroku creds and env variables needed?

**Comment by micahalcorn** [comment]
It looks like the current release is now 2️⃣.7️⃣.1️⃣:six: 🐍

**Comment by micahalcorn** [comment]
Closing in favor of https://github.com/OriginProtocol/origin-website/issues/562 😁
