### ISSUE TITLE
Remove excess space between team page sections

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-website#205]
The background panes on the team page cause a bit too much space to occur between the advisors and the investment funds. Find a way to reduce this without breaking the layout.

![40361835-9e4b5392-5d98-11e8-9e41-bec315da0ce7](https://user-images.githubusercontent.com/273937/40867889-82c7825c-65cd-11e8-9ca9-79991c151ed6.png)

**Comment by avidsapp** [comment]
Addressed with pull request #261

**Comment by mek32390** [comment]
@micahalcorn merged and tweaked #261 to resolve this.
