### ISSUE TITLE
Remove but still support /en on URLs

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-website#210]
Currently, when someone visits https://www.originprotocol.com, they are redirected to https://www.originprotocol.com/en. This results in people sharing the English version of the website around the web, which distorts our Google Analytics traffic to appear as if more visitors are English-speaking than is the reality. The auto-redirect should be removed, but /en should still be supported.

**Comment by joshfraser** [comment]
Just wanted to bump this issue. It bugs me every time I see people sharing links to the /en version of our site which breaks the nice automatic language-detection feature that we have.

**Comment by micahalcorn** [comment]
Hi @ericsteen 🙏 I've sent you an invitation to join the organization as a collaborator. Once you accept that, I will be able to assign the issue to you.

**Comment by acenario** [comment]
Hi! I'd like to take a stab at this! May not be able to do it today, but can take it on this week with a few other issues.

**Comment by acenario** [comment]
> Hi! I'd like to take a stab at this! May not be able to do it today, but can take it on this week with a few other issues.

Quick question: Should only /en/ be set to the main URL? Or should all english languages including en_GB also lead to the root url?

**Comment by joshfraser** [comment]
Thanks @acenario. We don't currently differentiate between the different flavors of English, so just /en/ should be fine.

**Comment by acenario** [comment]
@joshfraser Should only the homepage be fixed for /en/ or all pages remove the /en/ if there was no /en/ to begin with.
