### ISSUE TITLE
Update social links in our website footer

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/origin-website#212]
We're starting to have a lot of social links in our footer. We would like to:

- Split them into two columns
- Prefix them with their social logos for faster recognition
- Add YouTube (http://www.youtube.com/c/originprotocol)
- Add WeChat and display the QR code on hover (coming soon)

**Comment by mek32390** [comment]
I can do this one if you want to assign it to me. On the go right now.

**Comment by joshfraser** [comment]
And here's the QR code for our Wechat account that should show up when you mouseover that link. There is no URL destination for the click.

![screenshot 2018-06-13 19 17 33](https://user-images.githubusercontent.com/982234/41387940-7405ca06-6f3e-11e8-8248-3618c2f989ed.png)
