### ISSUE TITLE
Add hashtag-able links to developer landing page

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin-website#224]
Now that @micahalcorn made our beautiful landing page with https://github.com/OriginProtocol/origin-website/pull/222, a finishing touch would be to allow us to deep-link to headings on the page. E.g. `http://originprotocol.com/developers#call` to jump to the info on engineering call. 

(The new landing page is at this time not deployed on homepage, but visible [here](https://originprotocol-com-micah.herokuapp.com/en/developers).)

This should just mean adding tags like `<a name="foo">` to key parts of the page. 

Off the cuff, I'd recommend these, going down the page:

- http://originprotocol.com/developers#repos
- http://originprotocol.com/developers#contributing
- http://originprotocol.com/developers#resources
- http://originprotocol.com/developers#documentation
- http://originprotocol.com/developers#call
- http://originprotocol.com/developers#discord

Even if not surfaced, it will be good for us to have these available for e.g. linking someone right to information about our ENG Call. 

BONUS POINTS: show the cool "🔗" icon like github does when you hover over a linkable heading, which gives you the url for that link. :)

**Comment by mek32390** [comment]
@wanderingstan I added all the tags. Do you have an example for the bonus you are mentioning? I have an idea, but an example would make it more clear.

**Comment by micahalcorn** [comment]
Icon: https://fontawesome.com/icons/link?style=solid

UX: Hover over "Tests" [here](https://github.com/OriginProtocol/origin-js#tests)

**Comment by micahalcorn** [comment]
Done via #229 ✅
