### ISSUE TITLE
Background diamonds broken on large screen sizes

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/origin-website#230]
I think the background diamonds got messed up again when viewed on large screens. Maybe the css changed with the addition of the developer page? 

The text in the features section of the index page is covered by the background pane.

![image](https://user-images.githubusercontent.com/982234/42139945-24357d0c-7d4c-11e8-8bea-d1e185d3e843.png)

**Comment by micahalcorn** [comment]
Done via #233 ✅
