### ISSUE TITLE
Change heading on footer and remove address

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-website#237]
The word "Documentation" should be replaced with "Resources" and the full address should be removed.

![42252539-f52a0210-7ef1-11e8-9033-a5f0873d1164](https://user-images.githubusercontent.com/273937/42253129-0cdc2c5a-7ef5-11e8-908f-3aee540b5abc.png)

**Comment by shoutoutloud** [comment]
Hi. Can I work on this issue?

**Comment by micahalcorn** [comment]
@shoutoutloud sure, thanks. 🙏

**Comment by micahalcorn** [comment]
@shoutoutloud sure, thanks. 🙏 I've added you as a collaborator, so you don't need to fork the repo. Just create your own branch, push it here, and then create a pull request and follow the instructions.

**Comment by shoutoutloud** [comment]
So if I am not wrong you want me to replace and delete things from footer. html.

**Comment by micahalcorn** [comment]
@shoutoutloud correct 👍

**Comment by shoutoutloud** [comment]
I am getting this error when i run 'python main.py'
![screenshot from 2018-07-04 09-44-02](https://user-images.githubusercontent.com/21352046/42256535-930d1328-7f6f-11e8-8cea-e68cba1201cf.png)

**Comment by joshfraser** [comment]
Our website is still running on python 2.7.  We'll upgrade it at some point (our bridge server is already Python 3), but it's just not a priority right now.

**Comment by shoutoutloud** [comment]
@joshfraser Sure.

**Comment by micahalcorn** [comment]
Done via #238 ✅
