### ISSUE TITLE
Support Twitter Cards

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-website#243]
We should add explicit [Twitter Card meta tags](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/markup.html) to the base html file.

**Comment by alexpgates** [comment]
@micahalcorn Since you beat me to the phishing warning markup fix, I could knock a couple out since I have an environment up and running. Mind adding me as a collaborator so I don't have to fork? If so, I'll get this one.

**Comment by micahalcorn** [comment]
Ah, sorry @alexpgates 💔 I figured I should fix that one since I'm the one that broke it.

Sure, I'll get you added. Feel free to pick up anything from [our project board](https://github.com/orgs/OriginProtocol/projects/2) if you want to look into something more interesting.

**Comment by micahalcorn** [comment]
Done via #247 ✅ Thanks @alexpgates! cc @andrewhyde
