### ISSUE TITLE
Presale form not alerting about missing fields

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin-website#258]
On presale form:
https://www.originprotocol.com/en/presale

We're no longer giving hints like "Please enter name", "Please enter email" when those are missing. Seems to work once, but no more. 

Network log shows the `POST` is not even getting sent. Recaptcha may be to blame, as it intercepts the form submission. 

@micahalcorn , I'm gonna look more at this tomorrow, but maybe you have an idea out of the gate?

**Comment by wanderingstan** [comment]
Issue seems to be with [`flask-recaptcha`](https://github.com/OriginProtocol/flask-recaptcha). 

If `token` is not defined (as on first execution), then our code gets called as part of `grecaptcha.execute(recaptchaId);`. But on subsequent executions, this function just falls through doing nothing. 
```javascript
                      document.getElementById("presale").addEventListener("submit", function(event){
                        event.preventDefault()
                        var token =   grecaptcha.getResponse(recaptchaId);
                        // if token is not found, it means that user dodged the
                        // recaptcha somehow. Execute grecatcha again
                        if (!token) {
                          // trigger validation
                          grecaptcha.execute(recaptchaId);
                          return;
                        }
                      });
```
https://github.com/OriginProtocol/flask-recaptcha/blob/master/flask_recaptcha.py#L101-L110

This code is our fork of the original `flask-recaptcha` ( https://github.com/mardix/flask-recaptcha/blob/master/flask_recaptcha.py ) , by @Gzing  which was made (I think) to get the "invisible" recaptcha working: https://github.com/OriginProtocol/origin-website/pull/103

I suspect the underlying recaptcha javascript code has changed on us. 

@Gzing, do you have any bandwidth to look into this?

**Comment by tomlinton** [comment]
I can take a look at this @wanderingstan. I'll combine it with moving the `flask-recaptcha` code into `origin-website` like I mentioned in Discord.

**Comment by tomlinton** [comment]
Put a PR up for this @wanderingstan . Basically `flask-recaptcha` didn't handle multiple submits of the form so it didn't really work with the server side validation we have (it needed to be reset each time, or the token saved for later requests). Let me know if you have any questions. :smiley_cat:
