### ISSUE TITLE
Developers page is not translated

### ISSUE THREAD

**Issue by mek32390** [OriginProtocol/origin-website#269]
The Developers page is not translated. I will add the correct tags to it to allow it to be translated

**Comment by micahalcorn** [comment]
[That was a conscious decision](https://github.com/OriginProtocol/origin-website/commit/2989f67cc0bf2723a89cd0c1c208dda0ce8b6e52#diff-1e715ef477d560e7b4530853704d1f42). As I recall from the discussion, English speaking is a prerequisite for contributing and developing with Origin. @wanderingstan ❔

**Comment by mek32390** [comment]
oh yes, I do remember now. I'll hold off until @wanderingstan gives the OK!

**Comment by micahalcorn** [comment]
I will close this unless the plan changes.
