### ISSUE TITLE
Fix Crowdin integration

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin-website#276]
(Just dumping thoughts so I can pick this up later...)

If i understand correctly: 

Currently crowdin can't merge chinese languages because we're only using the two-letter language code (e.g. `en` for english), while for Chinese we also need locale to differenciate simplified and traditional, but both would just be `zh`. 

![image](https://user-images.githubusercontent.com/673455/44494822-92691e80-a62a-11e8-8fb2-62f8cc4f9df1.png)

Google Translator Toolkit (which we've used in the past) used a quasi-nonstandard language code similar to [BCP 47](http://www.rfc-editor.org/rfc/bcp/bcp47.txt), but with underscores instead of hyphens.

Crowdin does not have an explicit BCP 47 code option, but `osx_locale` seems to be exactly that, with hyphnes. (Or `crowdin_code`, though that doesn't appear to be file template option.)

Code to get list of crowdin lang codes:
```
curl https://api.crowdin.com/api/supported-languages
```

So I suggest we use `osx_locale`, and modify our code to change the hyphens to underscores as needed (if needed?) by `flask-babel`.

List of language codes:

http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry

**Comment by micahalcorn** [comment]
Assuming this is not longer relevant after the recent localization efforts 🤞
