### ISSUE TITLE
Translations - Hebrew

### ISSUE THREAD

**Issue by Kentoseth** [OriginProtocol/origin-website#29]
For anybody wishing to contribute to the translations:

https://github.com/OriginProtocol/company-website/blob/master/translations/he/LC_MESSAGES/messages.po

You add the translated-versions under `msgstr ""`

Example:

```
msgid "Hello"
msgstr "Bonjour"
```

See the German translation as an example:

https://github.com/OriginProtocol/company-website/blob/master/translations/de/LC_MESSAGES/messages.po

**Comment by micahalcorn** [comment]
Moved to [CrowdIn](https://goo.gl/PqT326) 🇮🇱
