### ISSUE TITLE
Serve Origin.js From HTTP

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-website#299]
[This](https://github.com/OriginProtocol/origin-website/blob/master/views/web_views.py#L236-L248) won't work with monorepo. I suppose that we could potentially do it using [the deprecated origin-js](https://github.com/OriginProtocol/origin-js/releases), but, according to the comments, we should use Nginx or a CDN.

**Comment by nick** [comment]
Don't think this is relevant with the rewrite
