### ISSUE TITLE
⬅️ Right-To-Left Creator Page

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-website#330]
The [Marketplace Creator landing page](https://originprotocol.com/creator) has been merged and deployed, but it does not support right-to-left languages, such as [Hebrew](https://www.originprotocol.com/he/creator) and [Arabic](https://www.originprotocol.com/ar/creator). I think that the graphics are probably passable if flipped horizontally. Otherwise, it should just be a matter of cleaning up some padding, margin, and text alignment. The actual text translations are a separate concern.

**Comment by drewmo** [comment]
I can handle this.

**Comment by micahalcorn** [comment]
@drewmo let me know if you see any assets that require a r-t-l-specific version.

**Comment by drewmo** [comment]
@micahalcorn You mean if there is an image or something that needs to be flipped?

What about stuff like [this?](https://www.originprotocol.com/static/img/purple-censorship.svg) Do we have translated versions?

**Comment by micahalcorn** [comment]
@drewmo I mean anything that doesn’t work by simply flipping it. We’ll hold off on translating images like that for now.

**Comment by drewmo** [comment]
@micahalcorn I've gone as far as I can on this until the images are fixed. The [blue coins](), [purple censorship](), and [green coins]() all either have text or logos that don't support flipping or there is a hard edge for fitting to the middle which looks strange when flipped:

![image 2-6-19 at 8 57 pm](https://user-images.githubusercontent.com/7915652/52391411-dd98b180-2a51-11e9-9e74-a1985165556c.jpg)

Up to you if you want to pull my changes as it at least fixes the issues with alignment and margins.
