### ISSUE TITLE
Featured Investor Videos

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-website#431]
As reported by @aquarterofaninja, the link to watch the featured investor video is broken.

Also, the styling is broken on mobile.

(zoomed for visibility)

![DB1DBA8C-2EE3-466F-872C-506CF212E0D1](https://user-images.githubusercontent.com/273937/66372259-87b14a80-e9e0-11e9-8a79-afd4fb85848b.png)

-----

If you need help, please ask in our [#engineering channel on Discord](http://www.originprotocol.com/discord). If you want to file an issue for a feature, bug, or discussion, please make an attempt to confirm that it does not already exist here in GitHub.

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by sparrowDom** [comment]
fixed via: https://github.com/OriginProtocol/origin-website/pull/433
