### ISSUE TITLE
Mobile Footer Bleed

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-website#440]
This is pretty low priority considering that this page automatically redirects.

![6F4816BE-1F09-4726-A7C0-5B838328CAD6](https://user-images.githubusercontent.com/273937/67591016-407dc600-f711-11e9-955f-0d95eee2790f.png)

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by debraycodes** [comment]
How do you access this page?

**Comment by uzairali19** [comment]
Hello @micahalcorn, 

Is this issue still open?
Is this assigned to someone yet?
If not I would like to take on this issue.
