### ISSUE TITLE
Dshop landing page revamp

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/origin-website#549]
[Here is the design](https://zpl.io/awKqv3D) for the new Dshop landing page. 

For mobile please see [here](https://zpl.io/VqolqnZ) and [here](https://zpl.io/2EMPAKn).

Note that links at the top are just in-page links that take you to the relevant section on the page.

**Comment by sparrowDom** [comment]
tnx @gullible1 forgot to close this one.
