### ISSUE TITLE
Deprecated Heroku Stack

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-website#562]
From Heroku:

> Your recently built app originprotocol-com is using the Heroku-16 [stack](https://devcenter.heroku.com/articles/stack), which [is deprecated](https://devcenter.heroku.com/changelog-items/1958).
> 
> From May 1st 2021, Heroku-16 will be end-of-life, and apps using it will no longer receive security updates, and be run at your own risk.
> 
> From June 1st 2021, builds will no longer be allowed for Heroku-16 apps.
> 
> Please [upgrade to a newer stack](https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack) as soon as possible.
> 
> See the [Heroku-16 End-Of-Life FAQ](https://help.heroku.com/0S5P41DC/heroku-16-end-of-life-faq) for more details.

**Comment by micahalcorn** [comment]
I tried updating this and discovered that we won't be able to upgrade Heroku without upgrading Python.

https://devcenter.heroku.com/articles/python-support#supported-runtimes

Need to upgrade from python-2.7.14 to python-3.6.12 😐

**Comment by mikeshultz** [comment]
Less than 60 days now.

CC @joshfraser
