### ISSUE TITLE
Upgrade to Python 3

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-website#566]
Since [Python 2 has reached its end-of-life](https://www.python.org/doc/sunset-python-2/) and [our Heroku stack has been deprecated](https://github.com/OriginProtocol/origin-website/issues/562), we should upgrade our website from python-2.7.14 to at least python-3.6.12.

**Comment by mikeshultz** [comment]
python 2 also makes this super hard to work on.
