### ISSUE TITLE
Two decimal price precision on dashboard

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-website#591]
[Our token dashboard](https://www.originprotocol.com/dashboard) shows the price of OGN. But if the price is $2.30, for example, it will be displayed as "$2.3". We should always show two decimals because the denomination is US dollars.

**Comment by SkyC0der** [comment]
Has this issue been fixed?

**Comment by micahalcorn** [comment]
> Has this issue been fixed?

I believe it has been.
