### ISSUE TITLE
Upcoming & Past NFT Drops

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-website#602]
Replace the current group of logos on the homepage with two sections of cards depicting upcoming and past drops. The past section should only show three but be expandable with a "View More" button. We probably don't need to worry about actual pagination yet. The cards should be left-aligned so that any remainders beyond the last multiple of three appears on the left rather than the center. All of the content should be fetched from a Launchpad API.

Going forward, the images are provided by creators via the builder (Twitter share image) but we may need to hardcode some for past drops or insert them into the Launchpad db. Rather than pull every event into this page automatically, they should require whitelisting via our admin dashboard. In addition to activating them for display on this page, we might also want to override the artist name and collection name shown under the image. Let's treat this section as a curated editorial rather than an automated feed.

For the upcoming drops, rather than showing a countdown or a specific time, I think we can just start with showing an abbreviated date (e.g. 6/12). The entire element (card + text) should be clickable and link to the URL of the drop's homepage.

**Comment by franckc** [comment]
@cipherzzz I'm hoping we can pull the drop data from the new *drops* table being added as part of PR #1146

**Comment by micahalcorn** [comment]
Forgot to link to the design 🤦 https://zpl.io/anB1zzY

**Comment by cipherzzz** [comment]
I see that https://github.com/oplabs/launchpad/pull/1146 is merged so I'll start there. I'm wondering how we would handle override artist and event names, though.

**Comment by franckc** [comment]
Yes, that is a great question regarding artist and event name. It is unclear to me where we could get that information from in our current DB model.

It might be available as one of the key/value pair the builder stores in the 'site_meta' table. Though doing a quick inspection of that table's data in production, I could not find it. Maybe @shahthepro or @micahalcorn would know.

Otherwise, we'll have to look at alternatives. Maybe we could consider adding event_name and artist_name to the drops table? We would also have to figure how that gets populated. Via admin or the builder?

**Comment by shahthepro** [comment]
@franckc @cipherzzz There's a key/value pair in DB with `aboutSections` as key. It's an array that include's the artist's name and images for the sites built with builder. For older sites, we may have to hard-code the overridden values.

**Comment by micahalcorn** [comment]
@franckc @cipherzzz maybe we start by just adding two new fields like heading and subheading. For now, we can fill out both in admin when we whitelist one for display on the site. Then, along the way, we can see if there are some good user-generated values that we can autopopulate or eventually use automatically. Like I was saying above, this should start out as more of a curated, editorial feature rather than an automatic feed.

**Comment by franckc** [comment]
@micahalcorn's suggestion sgtm... @cipherzzz what do you thinkzzz?

**Comment by cipherzzz** [comment]
@micah - micahhhhh - what's up with the stmt, `Replace the current group of logos on the homepage`. Not seeing that you're talking about

**Comment by franckc** [comment]
On the homepage, scroll down and look for "Never miss a drop". You'll see a bunch of logos there.
