### ISSUE TITLE
Make sure Celery is retrying jobs

### ISSUE THREAD

**Issue by ryana** [OriginProtocol/origin-website#72]
It just dawned on me I did not check to see how Celery retries. I'll take a look this week unless someone beats me to the punch and verifies this works as expected (retries job up to a reasonable number of times before failing for good).

**Comment by hucares** [comment]
Another thing that might be cogent is alerting on stale jobs. Delayed job queues generally do a pretty good job of retrying things but not flushing out dead or weird jobs.

**Comment by micahalcorn** [comment]
Assuming that nothing is broken here 😬
