### ISSUE TITLE
Index background image overflowing

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin-website#74]
On mobile safari iOS on iPad mini

![img_0188](https://user-images.githubusercontent.com/673455/35685346-b1e2cf02-0726-11e8-8331-85800ca2f985.PNG)

**Comment by micahalcorn** [comment]
This issue appears to be specific to Safari browsers. If a height of `100%` is set and the containing block's height is not defined, Safari will resolve this to height `auto` whereas Chrome, Firefox, etc calculate the actual height of the containing block. If possible, all of these height calculations should be avoided in favor of flexboxes.

**Comment by MrBeDiff** [comment]
agreed with Micah

**Comment by micahalcorn** [comment]
Those were the days. 😅
